#  Kopiere den Inhalt in die Zwischenablage und füge diesen dann in ein File 
#  mit dem Namen: Beeceptor.http in VS Code ein

@url = https://ca91e472be78a43e81f5.free.beeceptor.com

### Als erstes erstellen wir ein paar neuen User

POST {{url}}/api/users
Content-Type: application/json

{
  "first_name": "Fabian",
  "last_name": "Graf",
  "age": 25,
  "is_active": true
}

### Dann rufen wir die erstellten User ab
GET {{url}}/api/users

# Wir merken uns die Id des ersten Users
@id = a0fe322d617cd57532bc

### Get single user
GET {{url}}/api/users/{{id}}

### Get single user  (Not found)
GET {{url}}/api/users/64e234c636203e876d47d

### Update User mit PUT 
PUT {{url}}/api/users/{{id}}
Content-Type: application/json

{
  "first_name": "Fabienne",
  "last_name": "Mustermann",
  "age": 20,
  "is_active": true
}

### Den veränderten Record abrufen
GET {{url}}/api/users/{{id}}


### Update user mit Patch
PATCH  {{url}}/api/users/{{id}}
Content-Type: application/json

{
      "age": 20,
  "is_active": false
}

### Den veränderten Record abrufen
GET {{url}}/api/users/{{id}}

### Delete todo (Bitte Id anpassen)
DELETE  {{url}}/api/users/{{id}}

### Versuch den gelöschen Record erneut zu lesen
GET {{url}}/api/users/{{id}}

